replicaCount: 1

image:
  repository: zoryanayaremko/aiops-quality-project
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  MODEL_PATH: "model/model.joblib"
  GITLAB_WEBHOOK_URL: ""
