config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}

    extraScrapeConfigs: |
      - job_name: aiops-quality-project-logs
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_app
            action: keep
            regex: aiops-quality-project
